version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: "@wdio/spec-reporter"
    versions:
    - 7.4.3
    - 7.5.2
  - dependency-name: postcss
    versions:
    - 8.2.5
    - 8.2.9
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.2.2
  - dependency-name: open
    versions:
    - 8.0.5
  - dependency-name: caniuse-db
    versions:
    - 1.0.30001185
    - 1.0.30001191
    - 1.0.30001207
  - dependency-name: "@storybook/addon-backgrounds"
    versions:
    - 6.1.17
    - 6.1.18
    - 6.2.7
  - dependency-name: "@wdio/sync"
    versions:
    - 7.3.0
  - dependency-name: yeoman-generator
    versions:
    - 5.2.0
  - dependency-name: wdio-image-comparison-service
    versions:
    - 2.3.0
  - dependency-name: whatwg-fetch
    versions:
    - 3.6.2
  - dependency-name: "@babel/core"
    versions:
    - 7.13.13
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: marked
    versions:
    - 0.7.0
  - dependency-name: "@wdio/local-runner"
    versions:
    - 7.0.0
