language: node_js
sudo: false
node_js:
  - "12"
os:
  - linux
# addons:
#   firefox: latest
#   chrome: stable
#   browserstack:
#     username: BROWSERSTACK_USER
#     access_key: BROWSERSTACK_KEY
script:
  - npm test -- --verbose
#  - npm run e2e -- --verbose
cache:
  directories:
    - node_modules
# matrix:
#     exclude:
#         - os: osx # skip this because on Travis, node.js segfaults on osx+node 9
#           node_js: "9"
