name: Automerge PR
on:
  pull_request:
    types: [labeled, unlabeled, synchronize, edited, unlocked]
  pull_request_review:
    types: [submitted]
  check_suite:
    types: [completed]
    status: success
env:
  BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
jobs:
  visual_regression_tests:
    if: contains(github.event.pull_request.labels.*.name, 'ready to merge')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: BrowserStackLocal env setup
        uses: "browserstack/github-actions/setup-env@master"
        with:
          username: ${{ secrets.BROWSERSTACK_USER }}
          access-key: ${{ secrets.BROWSERSTACK_KEY }}
          build-name: BUILD_INFO
          project-name: REPO_NAME

      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Start BrowserStackLocal
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: start
          local-identifier: random
          # local-logging-level: all-logs

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Visual regression tests
        run: npm run e2e -- --verbose

      - name: Stop BrowserStackLocal
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: stop
  try_to_merge:
    if: contains(github.event.pull_request.labels.*.name, 'ready to merge')
    runs-on: ubuntu-latest
    needs: visual_regression_tests
    steps:
      - name: Try to automerge PR ${{ github.event.number }}
        uses: "pascalgn/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: "${{ secrets.ACTIONS }}"
          MERGE_LABELS: "ready to merge,!work in progress!,!blocked,!needs: code updates,!needs: additional info,!needs: AT updates,!needs: changelog,!ready: branch testing,!ready: browser testing"
          MERGE_REMOVE_LABELS: Ready to merge
          MERGE_METHOD: squash
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_RETRIES: 3
          MERGE_RETRY_SLEEP: 10000
          UPDATE_LABELS: "ready to merge,!work in progress!,!blocked"
          UPDATE_METHOD: rebase
