# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To view the configuration, go to: .github/labeler.yml
name: Auto-label PRs

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled
      - convert_to_draft
      - ready_for_review
  pull_request_review:
    types: [submitted]

env:
  TOKEN: "${{ secrets.GITHUB_TOKEN }}"

# Separate jobs can run concurrently
jobs:
  triage:
    name: Apply triage labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v3
        with:
          repo-token: ${{ env.TOKEN }}

  mergeable:
    name: Label a PR's merge status
    runs-on: ubuntu-latest

    steps:
      - name: Flag ready to merge
        # Add a ready to merge label if the PR is approved
        # ensure the PR is not on hold, in-progress, or blocked & doesn't have any pending
        # requirements still to do like needing a changelog or AT updates
        if: |
          !contains(github.event.pull_request.labels.*.name, 'on hold') &&
          !contains(github.event.pull_request.labels.*.name, 'work in progress') &&
          !contains(github.event.pull_request.labels.*.name, 'blocked') &&
          !contains(github.event.pull_request.labels.*.name, 'needs:*') &&
          !contains(github.event.pull_request.labels.*.name, 'ready:*') &&
          github.event.review.state == 'approved'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ env.TOKEN }}
          labels: ready to merge
      - name: Remove ready to merge flag
        # Remove the ready to merge label if the PR is not approved or certain labels are added
        if: |
          !contains(github.event.pull_request.labels.*.name, 'on hold') &&
          !contains(github.event.pull_request.labels.*.name, 'work in progress') &&
          !contains(github.event.pull_request.labels.*.name, 'blocked') &&
          !contains(github.event.pull_request.labels.*.name, 'needs:*') &&
          !contains(github.event.pull_request.labels.*.name, 'ready:*') &&
          github.event.review.state == 'approved'
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ env.TOKEN }}
          labels: ready to merge

  in-progress:
    name: Flag a PR as work-in-progress if in draft
    runs-on: ubuntu-latest

    steps:
      - name: Flag work in progress
        if: |
          github.event.pull_request.draft == true &&
          !contains(github.event.pull_request.labels.*.name, 'on hold') &&
          !contains(github.event.pull_request.labels.*.name, 'blocked')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ env.TOKEN }}
          labels: work in progress
