# This workflow will build and run the test suite
# on all opened and updated (and labeled) PRs where
# at least one file does not match paths-ignore.
name: Build & test

on:
  # manual run
  workflow_dispatch:
    branding:
      icon: eye
  # Build when a PR
  pull_request:
    types: [opened, synchronize, labeled, ready_for_review]
    # Will only run if files other than these are edited
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE/**"
      - ".storybook/**"
      - "docs/**"
      - "generators/**"
      - "**/*.md"
      - "**/*.text"
  # Build when PRs are merged into master/main
  push:
    branches: [master, main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # For webdriver script
  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
  BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}

  # Turn this on to debug an action
  # GITHUB_CONTEXT: ${{ toJson(github) }}
jobs:
  build:
    name: Compile project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    # Confirm that the PR is not in draft
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    steps:
      # Turn this on to debug an action
      # - run: echo "$GITHUB_CONTEXT"

      - name: Checkout repository
        uses: actions/checkout@v2

      # Configures the node version used on GitHub-hosted runners
      - name: Configure node version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # Caching speeds up the npm install step
      - name: Cache node modules
        id: cache
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      # Caching speeds up the npm install step
      # - name: Cache compiled assets
      #   id: cache-compiled
      #   uses: actions/cache@v2
      #   with:
      #     path: |
      #       elements/*/dist
      #     key: ${{ runner.os }}-build-${{ github.sha }}

      # - name: Remove package-lock
      #   if: steps.cache.outputs.cache-hit != 'true' || failure()
      #   run: rm package-lock.json

      - name: Install dependencies
        # if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      # Only commit the package-lock if this is the push to master
      # - name: Commit package-lock.json
      #   if: contains(github.event.push.ref, 'master') || contains(github.event.push.ref, 'main')
      #   uses: EndBug/add-and-commit@v5
      #   with:
      #     message: "Commit package-lock.json from ${{ github.event.push.sha }}"
      #     add: package-lock.json

      - name: Build
        id: build
        # if: steps.cache-compiled.outputs.cache-hit != 'true'
        run: npm run build

      # Upload compiled assets to make them available for downstream jobs
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: compiled-assets
          path: elements/*/dist/*
          if-no-files-found: error

  # Test command can run concurrent with e2e so it downloads the
  # compiled assets from the build and uses those instead of reinstalling.
  test:
    name: Run test suite (wct)
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Caching speeds up the npm install step
      - name: Access cached node modules
        id: get-node-cache
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Access compiled assets
        uses: actions/download-artifact@v2
        id: download-compiled-assets
        with:
          name: compiled-assets
          path: elements/*/dist/*

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: elements

      - name: Run tests
        run: npm test -- --build=false --verbose

  # E2E command can run concurrent with test so it downloads the
  # compiled assets from the build and uses those instead of reinstalling.
  # Only run visual tests if the PR is labeled "ready to merge" or "run e2e"
  e2e:
    name: Visual regression testing
    needs: build
    if: contains(github.event.pull_request.labels.*.name, 'ready to merge') || contains(github.event.pull_request.labels.*.name, 'run e2e')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
    steps:
      - name: BrowserStack environment setup
        uses: "browserstack/github-actions/setup-env@master"
        with:
          username: ${{ secrets.BROWSERSTACK_USER }}
          access-key: ${{ secrets.BROWSERSTACK_KEY }}

      - name: Start BrowserStackLocal
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random
          # local-logging-level: all-logs

      - name: Checkout repository
        uses: actions/checkout@v2

      # Caching speeds up the npm install step
      - name: Access cached node modules
        id: get-node-cache
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: |
            ~/.npm
            **/node_modules
          key: ${{ runner.os }}-npm-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}

      - name: Access compiled assets
        uses: actions/download-artifact@v2
        id: download-compiled-assets
        with:
          name: compiled-assets
          path: elements/*/dist/*

      - name: Visual regression tests
        run: npm run e2e -- --verbose

      # Upload assets even if the e2e fails
      - name: Archive baseline images
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: visual-regression-snapshots
          path: |
            .tmp/
            test/vrt-baseline
            test/vrt-snapshots
          if-no-files-found: error

      - name: Stop BrowserStackLocal
        if: always()
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
