# This workflow will build and run the test suite
# on all opened and updated (and labeled) PRs where
# at least one file does not match paths-ignore.
name: Build & test
on:
  pull_request:
    types: [opened, synchronize, labeled]
    # Will only run if files other than these are edited
    paths-ignore:
      - ".github/ISSUE_TEMPLATE/**"
      - ".github/PULL_REQUEST_TEMPLATE/**"
      - ".storybook/**"
      - ".storybook_out/**"
      - "docs/**"
      - "generators/**"
      - "**/*.md"
      - "**/*.text"
env:
  BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_KEY }}
  BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USER }}
jobs:
  build_test_e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Caching speeds up the npm install step
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: npm install

      - name: Build
        id: build
        run: npm run build

      - name: Run tests
        run: npm test -- --verbose

      # Only run visual tests if the PR is labeled "ready to merge" or "run e2e"
      - name: Start BrowserStackLocal
        if: contains(github.event.pull_request.labels.*.name, 'ready to merge') || contains(github.event.pull_request.labels.*.name, 'run e2e')
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: start
          local-identifier: random
          # local-logging-level: all-logs

      - name: Visual regression tests
        if: contains(github.event.pull_request.labels.*.name, 'ready to merge') || contains(github.event.pull_request.labels.*.name, 'run e2e')
        run: npm run e2e -- --verbose

      - name: Stop BrowserStackLocal
        if: contains(github.event.pull_request.labels.*.name, 'ready to merge') || contains(github.event.pull_request.labels.*.name, 'run e2e')
        uses: "browserstack/github-actions/setup-local@master"
        with:
          local-testing: stop
